In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
path = "data"
f = os.listdir(path)[0]
f

'data.csv'

In [3]:
df = pd.read_csv(os.path.join(path, f))
print(f"Row : {df.shape[0]}, \t Columns : {df.shape[1]}")
df.head(3)

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (1,11,13) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

Row : 999442, 	 Columns : 18

,master_seq,isbn13,vol,title,author,publisher,pub_date,add_code,price,img_url,description,kdc_class_no,title_replace,author_replace,pub_date_2,is_coll_aladin,is_coll_naver,isbn_origin
0,115982,9780761921585,cloth,Designing for learning:six elements in constru...,"George W. Gagnon, Jr., Michelle Collay","Corwin Press, Calif.",NaN,NaN,121081.0,http://image.aladin.co.kr/product/519/70/cover...,NaN,NaN,designingforlearningsixelementsinconstructivis...,NaN,2000-12-29,Y,Y,0761921583 (cloth)
1,115983,9780335201204,NaN,"Changing school subjects:power, gender, and cu...",Carrie Paechter,Open University Press,NaN,NaN,208260.0,http://image.aladin.co.kr/product/502/40/cover...,NaN,NaN,"changingschoolsubjectspower,gender,andcurriculum",NaN,2000-12-01,Y,Y,0335201202
2,115984,9780750707565,cased:alk.paper,Change forces:the sequel,Michael Fullan,Falmer Press,NaN,NaN,204230.0,http://image.aladin.co.kr/product/121/47/cover...,"[해외주문원서] 고객님의 요청으로 수입 주문하는 도서이므로, 주문취소 및 반품이 불...",NaN,changeforcesthesequel,NaN,1999-06-10,Y,Y,0750707569 (cased : alk. paper)

In [4]:
drop_columns = ['master_seq', 'vol', 'author', 'publisher', 'pub_date', 'add_code', 'price', 
         'img_url', 'author_replace', 'pub_date_2','is_coll_aladin', 'is_coll_naver', 'isbn_origin', 'title_replace']
df.drop(drop_columns, axis=1, inplace=True)
df.head()

,isbn13,title,description,kdc_class_no
0,9780761921585,Designing for learning:six elements in constru...,NaN,NaN
1,9780335201204,"Changing school subjects:power, gender, and cu...",NaN,NaN
2,9780750707565,Change forces:the sequel,"[해외주문원서] 고객님의 요청으로 수입 주문하는 도서이므로, 주문취소 및 반품이 불...",NaN
3,9780415183871,Children's reading choices,NaN,NaN
4,9780072322729,Classroom assessment:concepts and applications,PETER W. AIRASIAN IS PROFESSOR OF EDUCATION AT...,NaN

In [5]:
df.isna().sum()

isbn13               0
title                0
description     454287
kdc_class_no    361249
dtype: int64

In [6]:
df.dropna(axis=0, inplace=True)
print(df.shape)
df.isna().sum()

(390764, 4)

isbn13          0
title           0
description     0
kdc_class_no    0
dtype: int64

In [7]:
df.head()

,isbn13,title,description,kdc_class_no
99,9788995192740,(2001-2002년)일본의 구조개혁과 증권시장,이 책은 세계 2위의 경제대국이지만 구조개혁 지연으로 장기 불황에 신음하고 있는 일...,327.85
100,9788982412615,IBM 통합(Intergrated) 시스템,현장 실무자를 위한 IBM 서버 안내서. IBM AS/400D을 기능에 초점을 맞추...,4.145
101,9788975486456,(L=MS²학문의 기원)學習學,학습학 사상과 원형을 탐구한 책. 배우고 익히는 인간의 아름다움과 동시에 실천이라는...,370
102,9788982412738,인터넷에 점포차리기,"이제 전자상거래의 중심에 선다, 책 한권으로 인터넷 쇼핑몰 사업가로 화려한 변신! ...",326.165
103,9788952720016,"잘가라, 종이만화",디지털 만화가 쏟아지는 그 생생한 현장에서 온몸으로 부딪치며 깨우친 디지털 만화의 ...,657.102

In [8]:
df['kdc_class_no'] = df['kdc_class_no'].astype(float)
df['main_class'] = df['kdc_class_no'] // 100
df['sub_class'] = (df['kdc_class_no'] - (df['main_class'] * 100)) // 10
df.head()

,isbn13,title,description,kdc_class_no,main_class,sub_class
99,9788995192740,(2001-2002년)일본의 구조개혁과 증권시장,이 책은 세계 2위의 경제대국이지만 구조개혁 지연으로 장기 불황에 신음하고 있는 일...,327.8500,3.0,2.0
100,9788982412615,IBM 통합(Intergrated) 시스템,현장 실무자를 위한 IBM 서버 안내서. IBM AS/400D을 기능에 초점을 맞추...,4.1450,0.0,0.0
101,9788975486456,(L=MS²학문의 기원)學習學,학습학 사상과 원형을 탐구한 책. 배우고 익히는 인간의 아름다움과 동시에 실천이라는...,370.0000,3.0,7.0
102,9788982412738,인터넷에 점포차리기,"이제 전자상거래의 중심에 선다, 책 한권으로 인터넷 쇼핑몰 사업가로 화려한 변신! ...",326.1650,3.0,2.0
103,9788952720016,"잘가라, 종이만화",디지털 만화가 쏟아지는 그 생생한 현장에서 온몸으로 부딪치며 깨우친 디지털 만화의 ...,657.1018,6.0,5.0

In [9]:
df = df[(df['main_class'] == 0) & (df['sub_class'] == 0)]
drop_columns = ['kdc_class_no', 'main_class', 'sub_class']
df.drop(drop_columns, axis=1, inplace=True)
df.head()

,isbn13,title,description
100,9788982412615,IBM 통합(Intergrated) 시스템,현장 실무자를 위한 IBM 서버 안내서. IBM AS/400D을 기능에 초점을 맞추...
121,9788988557211,(단계별 실습에 의한)델파이 프로그래밍=Delphi programming,"비주얼형 객체지향 프로그래밍 언어로서 비중러 베이직, 비주얼 C++, 자바 등과 함..."
125,9788982412707,컴퓨터 활용 실습,컴퓨터를 잘 활용하기 위하여 반드시 알아 두어야 할 기초적인 내용으로 컴퓨터를 전공...
129,9788982412578,(아주 특별한)비주얼베이직6 게임과 프로젝트,중급자를 위한 비주얼 베이직6 교재이다. 비주얼 베이직 6를 활용한 게임 프로그래밍...
133,9788982412691,컴퓨터활용의 첫걸음:컴퓨터의 기초 윈도우즈와 인터넷 한글,컴퓨터를 잘 활용하기 위하여 반드시 알아야 할 기초적인 내용으로 컴퓨터를 전공하지 ...

In [10]:
df.to_csv(os.path.join(path, "target.csv"), index=False)